FROM node:16-alpine AS deps

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV production

RUN yarn build-storybook

RUN yarn global add serve

EXPOSE 5000

CMD ["serve", "-p", "5000", "storybook-static"]
