import { useCallback } from 'react';

import Head from 'next/head';
import { useTranslation } from 'next-i18next';

import { withAuth } from '@/components/HOCs';
import { actions, useAppDispatch } from '@/store';
import { Button, Typography } from '@/ui/core';

import css from './styles.module.css';

function HomePageRoot() {
  const { t } = useTranslation('home');
  const dispatch = useAppDispatch();
  const signOut = useCallback(() => {
    dispatch(actions.signOut());
  }, [dispatch]);

  return (
    <>
      <Head>
        <title>{t('home-page.html.title')}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={css.root}>
        <header>
          <Typography variant="heading1">{t('home-page.title')}</Typography>
        </header>

        <Button type="button" onClick={signOut} label={t('home-page.sign-out')!} />
      </main>
    </>
  );
}

export const HomePage = withAuth(HomePageRoot);
